pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
    buildscript {
        repositories {
            mavenCentral()
        }
        dependencies {
            classpath 'com.google.code.gson:gson:2.11.0'
        }
    }
}
